### ISSUE TITLE
Known Omron problems

### ISSUE THREAD

**Issue by kyle-github** [libplctag/libplctag#469]
The following tracks known Omron problems.

- [x] Issue [381](https://github.com/libplctag/libplctag.NET/issues/381) in the .Net wrapper project. Since 2.6.0 allowed element counts other than 1, some Omron array reads are failing.
- [ ] Issue #467 tracks incorrect packet size defaults.
- [ ] Issue #466 tracks the lack of support for tag listing with Omron PLCs.
- [ ] Issue #468 tracks need for core library support exposing PLC types and information in order to solve the BOOL array problem for Omron.
- [ ] #470
